superlists/urls.py
from django.conf.urls import include, url
from django.contrib import admin

# all lists views imported as: lists_views.view_name
from lists import views as lists_views

urlpatterns = [
    url(r'^$', lists_views.home_page, name='home'),
    url(r'^lists/(\d+)/$', lists_views.view_list, name='view_list'),
    url(r'^lists/(\d+)/add_item$', lists_views.add_item, name='add_item'),
    url(r'^lists/new$', lists_views.new_list, name='new_list'),
    url(r'^admin/', admin.site.urls),
]

lists/models.py
from django.db import models

# Create your models here.

class List(models.Model):
    pass

class Item(models.Model):
    text = models.TextField(default='')
    list = models.ForeignKey(List, default=None)

lists/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse

from lists.models import Item, List

# Create your views here.

def home_page(request):
    return render(request, 'home.html')

def view_list(request, list_id):
    list_ = List.objects.get(id=list_id)
    items = Item.objects.filter(list=list_)
    context = {
        'items': items,
    }
    return render(request, 'list.html', context)

def new_list(request):
    list_ = List.objects.create()
    Item.objects.create(text=request.POST['item_text'], list=list_)
    return redirect('/lists/%d/' % (list_.id,))

def add_item(request, list_id):
    list_ = List.objects.get(id=list_id)
    Item.objects.create(text=request.POST['item_text'], list=list_)
    return redirect('/lists/%d/' % (list_.id,))

def view_list(request, list_id):
    list_ = List.objects.get(id=list_id)
    context = {
        'list': list_
    }
    return render(request, 'list.html', context)

lists/templates/home.html
<html>
    <head>
        <meta charset="utf-8">
        <title>To-Do Lists</title>
    </head>
    <body>
        <h1>Start a new To-Do list</h1>
        <form method="POST" action="/lists/new">
            <input name="item_text" id="id_new_item" placeholder="Enter a to-do item" />
            {% csrf_token %}
        </form>
        <table id="id_list_table">
            {% for item in items %}
            <tr>
                <td>
                    {{ forloop.counter }}: {{ item.text }}
                </td>
            </tr>
            {% endfor %}
        </table>
    </body>
</html>

lists/templates/list.html
<html>
    <head>
        <meta charset="utf-8">
        <title>To-Do Lists</title>
    </head>
    <body>
        <h1>Your To-Do Lists</h1>
        <form method="POST" action="/lists/{{ list.id }}/add_item">
            <input name="item_text" id="id_new_item" placeholder="Enter a to-do item" />
            {% csrf_token %}
        </form>
        <table id="id_list_table">
            {% for item in list.item_set.all %}
            <tr>
                <td>
                    {{ forloop.counter }}: {{ item.text }}
                </td>
            </tr>
            {% endfor %}
        </table>
    </body>
</html>